project: gat50L_uw
method: random
program: cv_wandb.py
metric:
  name: val_loss
  goal: minimize
parameters:
  C_lasso:
    distribution: log_uniform_values
    max:  1.2 # 0.1823215567939546
    min:  0.02 # -3.912023005428146
  n_folds:
    value: 10
  S_threshold:
    distribution: uniform
    max: 0.5
    min: 0.3
  n_epochs:
    value: 700
  lr:
    distribution: log_uniform_values
    max: 0.1 # -2.3025850929940455
    min: 0.0001 # -9.210340371976182
  weight_decay:
    distribution: log_uniform_values
    max: 0.1 # -0.6931471805599453
    min: 0.0001 # -9.210340371976182
  cl1_hidden_units:
    distribution: categorical
    values:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
  cl2_hidden_units:
    value: 8
  h1_hidden_units:
    value: 8
  h2_hidden_units:
    value: 8
  ll_out_units:
    value: 2
  dropout:
    distribution: uniform
    max: 0.7
    min: 0
  lrscheduler_factor:
    value: 0.5
  model_name:
    value: "GAT_50L_uw"
  heads:
    distribution: categorical
    values:
      - 2
      - 3
      - 5
  K_cheby:
    value: 2
  depth:
    value: 2
